services:
  - type: web
    name: srf-backend
    env: node
    buildCommand: npm install && npm run build --workspace=srf-backend
    startCommand: npm run start:prod --workspace=srf-backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false